In [1]:
import cv2 #import cv2 # 영상처리 라이브러리
import matplotlib.pyplot as plt # 시각화( 이미지 띄우기 등)
import numpy as np # 배열처리

In [2]:
# 일반화
def calcArith(img, alpha, beta):
    output = np.zeros((h,w))
    for x in range(0,h):
        for y in range(0,w):
            output[x,y] = alpha * img[x,y] + beta
            for x in range(0,h):
                 for y in range(0,w):
                    if alpha * img[x,y] + beta > 255:
                        output[x,y] = 255
                    elif alpha * img[x,y] + beta < 0:
                        output[x,y] = 0
                    else:
                        output[x,y] = alpha * img[x,y] + beta
    return np.uint8(output)

In [3]:
# 이미지 불러오기
img = cv2.imread("images/Lenna.png", cv2.IMREAD_GRAYSCALE)
h,w = img.shape

print(h,w)

220 220


In [4]:
# 덧셈

#방법 1. 행렬(배열)의 특성을 이용하기

beta = 1
output1 = img+ beta
print(output1)


#방법 2. cv2 함수 이용하기

output2 = cv2.add(img,beta)
print(output2)

#방법 3. 반복문 이용하기 : 공학적 접근

output3 = np.zeros((h,w))
print(output3)
for x in range(0,h):
    for y in range(0,w):
        #g(x,y) = alpha * f(x,y) + beta
        output3[x,y] = img[x,y] + beta
print(output3)

[[169 169 168 ... 172 178 155]
 [169 168 168 ... 175 183 159]
 [170 167 168 ... 151 133 100]
 ...
 [ 60  62  65 ...  83  99 103]
 [ 57  62  62 ...  96 111 112]
 [ 54  62  60 ... 107 117 119]]
[[169 169 168 ... 172 178 155]
 [169 168 168 ... 175 183 159]
 [170 167 168 ... 151 133 100]
 ...
 [ 60  62  65 ...  83  99 103]
 [ 57  62  62 ...  96 111 112]
 [ 54  62  60 ... 107 117 119]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[169. 169. 168. ... 172. 178. 155.]
 [169. 168. 168. ... 175. 183. 159.]
 [170. 167. 168. ... 151. 133. 100.]
 ...
 [ 60.  62.  65. ...  83.  99. 103.]
 [ 57.  62.  62. ...  96. 111. 112.]
 [ 54.  62.  60. ... 107. 117. 119.]]


In [5]:
# 뺄셈

#방법 1. 행렬(배열)의 특성을 이용하기

beta = 1
output1 = img - beta
print(output1)


#방법 2. cv2 함수 이용하기

output2 = cv2.subtract(img,beta)
print(output2)

#방법 3. 반복문 이용하기 : 공학적 접근

output3 = np.zeros((h,w))
print(output3)
for x in range(0,h):
    for y in range(0,w):
        #g(x,y) = alpha * f(x,y) + beta
        output3[x,y] = img[x,y] - beta
print(output3)

[[167 167 166 ... 170 176 153]
 [167 166 166 ... 173 181 157]
 [168 165 166 ... 149 131  98]
 ...
 [ 58  60  63 ...  81  97 101]
 [ 55  60  60 ...  94 109 110]
 [ 52  60  58 ... 105 115 117]]
[[167 167 166 ... 170 176 153]
 [167 166 166 ... 173 181 157]
 [168 165 166 ... 149 131  98]
 ...
 [ 58  60  63 ...  81  97 101]
 [ 55  60  60 ...  94 109 110]
 [ 52  60  58 ... 105 115 117]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[167. 167. 166. ... 170. 176. 153.]
 [167. 166. 166. ... 173. 181. 157.]
 [168. 165. 166. ... 149. 131.  98.]
 ...
 [ 58.  60.  63. ...  81.  97. 101.]
 [ 55.  60.  60. ...  94. 109. 110.]
 [ 52.  60.  58. ... 105. 115. 117.]]


In [ ]:
# \곱셈

#방법 1. 행렬(배열)의 특성을 이용하기
alpha = 2
beta = 1
output1 = img * alpha
print(output1)


#방법 2. cv2 함수 이용하기

output2 = cv2.multiply(img,alpha)
print(output2)

#방법 3. 반복문 이용하기 : 공학적 접근

output3 = np.zeros((h,w))
print(output3)
for x in range(0,h):
    for y in range(0,w):
        #g(x,y) = alpha * f(x,y) + beta
        output3[x,y] = img[x,y] *alpha
print(output3)

In [ ]:
# 나눗셈

#방법 1. 행렬(배열)의 특성을 이용하기
alpha = 2
beta = 1
output1 = img / alpha
print(output1)


#방법 2. cv2 함수 이용하기

output2 = cv2.divide(img,alpha)
print(output2)

#방법 3. 반복문 이용하기 : 공학적 접근

output3 = np.zeros((h,w))
print(output3)
for x in range(0,h):
    for y in range(0,w):
        #g(x,y) = alpha * f(x,y) + beta
        output3[x,y] = img[x,y] / alpha
print(np.uint8(output3))

In [ ]:
calcArith(img, 1, 20) # 덧셈
calcArith(img, 1, -20) # 뺄셈
calcArith(img, 2, 0) # 곱셈
calcArith(img, 1/2, 0) # 나눗셈

In [ ]:
# 산술연산의 문제점 해결하기


In [ ]:
# 방법 1. 클램핑 : 음수 = 0 ,255 이상 = 255
img = cv2.imread("images/Lenna.png", cv2.IMREAD_GRAYSCALE)
output = np.zeros((h,w))
for x in range(0,h):
     for y in range(0,w):
        if alpha * img[x,y] + beta > 255:
            output[x,y] = 255
        elif alpha * img[x,y] + beta < 0:
            output[x,y] = 0
        else:
            output[x,y] = alpha * img[x,y] + beta
output[x,y] = alpha * img[x,y] + beta
print(img)
print(output)

In [ ]:
# 방법 2. 랩핑: 음수 = 0, 255 이상은
img = cv2.imread("images/Lenna.png", cv2.IMREAD_GRAYSCALE)
output = np.zeros((h,w))
for x in range(0,h):
     for y in range(0,w):
        if alpha * img[x,y] + beta > 255:
            output[x,y] = (alpha * img[x,y] + beta)//256
        elif alpha * img[x,y] + beta < 0:
            output[x,y] = 0
        else:
            output[x,y] = alpha * img[x,y] + beta
output[x,y] = alpha * img[x,y] + beta
print(img)
print(output)

In [ ]:
# 실습 3 논리연산

# 이미지 읽어오기
img = cv2.imread("images/Lenna.png", cv2.IMREAD_GRAYSCALE)
h, w =img.shape

print(h, w)
# 원 모양의 마스크 생성하기
mask = cv2.circle(np.zeros((h,w)), np.uint8(h/2, np.uint8w/2), 80, 255, -1)
mask - np.uint8(mask)

# cv2 사용해서 논리연산 수행히기
and_img = cv2. bitwise_and(img.mask)
or_img = cv2. bitwise_or(img.mask)
xor_img = cv2. bitwise_xor(img.mask)
not_img = cv2. bitwise_not(img.mask)
# 출력하기(시각화)
plt.subplot(2,3,1)plt.imshow(img.cmap = 'gray')
plt.subplot(2,3,2)plt.imshow(and_img.cmap = 'gray')
plt.subplot(2,3,3)plt.imshow(or_img.cmap = 'gray')
plt.subplot(2,3,4)plt.imshow(xor_img.cmap = 'gray')
plt.subplot(2,3,5)plt.imshow(not_img.cmap = 'gray')

In [ ]:
# 과제, 논리연산 공학적으로 구현하기

for x in range(0,h):
    for y in range(0,w):
        img[x,y]
        bin()
        for k in range(0,8):
            
            
# 1. 픽셀값의 잉진수
print(bin(181)[2:]) #string
print(bin(255([2:])))

# 2. 비교, 비트별로 논리연산
for k in range(0,8): 


In [ ]:
# 실습 4

#null transform : y = 1 * x + 0
null_img = np.zeros((h,w))
for x in range(0,h):
    for y in range(0,w):
        null_img[x,y] = a * img[x,y] + b
        
plt.subplot(1,2,1)plt.imshow(img.cmap = 'gray')
plt.subplot(1,2,2)plt.imshow(and_img.cmap = 'gray')

In [ ]:
#null transform : y = 1 * x + 0
a = -1
b = 255

null_img = np.zeros((h,w))
for x in range(0,h):
    for y in range(0,w):
        null_img[x,y] = a * img[x,y] + b
        
plt.subplot(1,2,1)plt.imshow(img.cmap = 'gray')
plt.subplot(1,2,2)plt.imshow(and_img.cmap = 'gray')

In [ ]:
a = -1
b = 255
gamma = 4
gamma_img = np.zeros((h,w))

for x in range(0,h):
    for y in range(0,w):
        null_img[x,y] = a * (img[x,y]/255)**(gamma) * 255
        
gamma_img = np.unit8(gamma_img)

plt.subplot(1,2,1)plt.imshow(img.cmap = 'gray')
plt.subplot(1,2,2)plt.imshow(and_img.cmap = 'gray')

In [ ]:
a = (255-0)/(200-50)
b = -a*50

ics_img = np.zeros((h,w))
for x in range(0,h):
    for y in range(0,w):
        if imt[x,y] < 50:
            ics_img[x,y] = 0
        elif img[x,y] > 200:
            ics_img[x,y]=255
        else
             ics_img[x,y] = a * img[x,y] + b
       
        
plt.subplot(1,2,1)plt.imshow(img.cmap = 'gray')
plt.subplot(1,2,2)plt.imshow(and_img.cmap = 'gray')

In [ ]:
a = (200-50)/(255-0)
b = 50

icc_img = np.zeros((h,w))
for x in range(0,h):
    for y in range(0,w):
        if imt[x,y] < 50:
            icc_img[x,y] = 0
        elif img[x,y] > 200:
            icc_img[x,y]=255
        else
             icc_img[x,y] = a * img[x,y] + b
       
        
plt.subplot(1,2,1)plt.imshow(img.cmap = 'gray')
plt.subplot(1,2,2)plt.imshow(and_img.cmap = 'gray')